CREATE TABLE admin(
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
  nameAdmin VARCHAR(255) COMMENT '',
  emailAdmin VARCHAR(255) COMMENT '',
  pwAdmin VARCHAR(255) COMMENT ''
) DEFAULT CHARSET UTF8 COMMENT '';
